#! /usr/bin/python3

#Base filters:
# query = ...
# search_titles = True/False
# has_image = True/False
# posted_today = True/False
# bundle_duplicates = True/False
# search_distance = ...
# zip_code = ...
#Section specific filters:
# min_price = ...
# max_price = ...
# make = ...
# model = ...
# min_year = ...
# max_year = ...
# min_miles = ...
# max_miles = ...
# min_engine_displacement = ...
# max_engine_displacement = ...
# language = 'af', 'ca', 'da', 'de', 'en', 'es', 'fi', 'fr', 'it', 'nl', 'no', 'pt', 'sv', 'tl', 'tr', 'zh', 'ar', 'ja', 'ko', 'ru', 'vi'
# condition = 'new', 'like new', 'excellent', 'good', 'fair', 'salvage'
# auto_cylinders = '3 cylinders', '4 cylinders', '5 cylinders', '6 cylinders', '8 cylinders', '10 cylinders', '12 cylinders', 'other'
# auto_drivetrain = 'fwd', 'rwd', '4wd'
# auto_fuel_type = 'gas', 'diesel', 'hybrid', 'electric', 'other'
# auto_paint = 'black', 'blue', 'brown', 'green', 'grey', 'orange', 'purple', 'red', 'silver', 'white', 'yellow', 'custom'
# auto_size = 'compact', 'full-size', 'mid-size', 'sub-compact'
# auto_title_status = 'clean', 'salvage', 'rebuilt', 'parts only', 'lien', 'missing'
# auto_transmission = 'manual', 'automatic', 'other'
# auto_bodytype = 'bus', 'convertible', 'coupe', 'hatchback', 'mini-van', 'offroad', 'pickup', 'sedan', 'truck', 'SUV', 'wagon', 'van', 'other'

#, 'auto_transmission':['manual','other']
#'posted_today': True,
